import type { Movimiento, Cuenta, TarjetaCredito, MetaAhorro, Categoria, Presupuesto } from "./types"

export const categorias: Categoria[] = [
  { id: "cat-1", nombre: "Sueldo", tipo: "Ingreso", color: "#10b981", icono: "DollarSign" },
  { id: "cat-2", nombre: "Ingresos Extra", tipo: "Ingreso", color: "#34d399", icono: "TrendingUp" },
  { id: "cat-3", nombre: "Arriendo/Dividendo", tipo: "Gasto", color: "#ef4444", icono: "Home" },
  { id: "cat-4", nombre: "Supermercado", tipo: "Gasto", color: "#f59e0b", icono: "ShoppingCart" },
  { id: "cat-5", nombre: "Transporte", tipo: "Gasto", color: "#3b82f6", icono: "Bus" },
  { id: "cat-6", nombre: "Bencina", tipo: "Gasto", color: "#8b5cf6", icono: "Fuel" },
  { id: "cat-7", nombre: "Servicios Básicos", tipo: "Gasto", color: "#ec4899", icono: "Zap" },
  { id: "cat-8", nombre: "Internet/Telefonía", tipo: "Gasto", color: "#06b6d4", icono: "Wifi" },
  { id: "cat-9", nombre: "Salud", tipo: "Gasto", color: "#14b8a6", icono: "Heart" },
  { id: "cat-10", nombre: "Farmacia", tipo: "Gasto", color: "#f97316", icono: "Pill" },
  { id: "cat-11", nombre: "Suscripciones", tipo: "Gasto", color: "#a855f7", icono: "Tv" },
  { id: "cat-12", nombre: "Delivery/Restaurantes", tipo: "Gasto", color: "#f43f5e", icono: "UtensilsCrossed" },
  { id: "cat-13", nombre: "Educación", tipo: "Gasto", color: "#6366f1", icono: "GraduationCap" },
  { id: "cat-14", nombre: "Entretenimiento", tipo: "Gasto", color: "#ec4899", icono: "Sparkles" },
  { id: "cat-15", nombre: "Ropa", tipo: "Gasto", color: "#8b5cf6", icono: "Shirt" },
  { id: "cat-16", nombre: "Ajuste/Corrección", tipo: "Ambos", color: "#64748b", icono: "Settings" },
]

export const cuentas: Cuenta[] = [
  {
    id: "cta-1",
    nombre: "Cuenta Corriente",
    banco: "Banco de Chile",
    saldoInicialMes: 850000,
    saldoFinalMesDeclarado: 420000,
    saldoCalculado: 0,
    activo: true,
  },
  {
    id: "cta-2",
    nombre: "Cuenta Vista",
    banco: "BancoEstado",
    saldoInicialMes: 120000,
    saldoCalculado: 0,
    activo: true,
  },
  {
    id: "cta-3",
    nombre: "Efectivo",
    banco: "N/A",
    saldoInicialMes: 50000,
    saldoCalculado: 0,
    activo: true,
  },
]

export const tarjetasCredito: TarjetaCredito[] = [
  {
    id: "tc-1",
    nombre: "Visa Santander",
    banco: "Santander",
    cupoTotal: 1500000,
    cupoDisponible: 980000,
    fechaFacturacion: 15,
    fechaPago: 10,
    tasaInteresMensual: 2.5,
    deudaActual: 520000,
    deudaFacturada: 320000,
    deudaNoFacturada: 200000,
  },
  {
    id: "tc-2",
    nombre: "Mastercard BCI",
    banco: "BCI",
    cupoTotal: 1000000,
    cupoDisponible: 750000,
    fechaFacturacion: 5,
    fechaPago: 25,
    tasaInteresMensual: 2.3,
    deudaActual: 250000,
    deudaFacturada: 150000,
    deudaNoFacturada: 100000,
  },
]

export const metasAhorro: MetaAhorro[] = [
  {
    id: "meta-1",
    nombre: "Fondo de Emergencia",
    objetivoCLP: 3000000,
    fechaObjetivo: "2026-12-31",
    aporteMensualSugerido: 250000,
    acumuladoCLP: 1200000,
    cuentaDestinoId: "cta-2",
    estado: "Activa",
  },
  {
    id: "meta-2",
    nombre: "Viaje a Europa",
    objetivoCLP: 2500000,
    fechaObjetivo: "2026-07-01",
    aporteMensualSugerido: 400000,
    acumuladoCLP: 800000,
    cuentaDestinoId: "cta-2",
    estado: "Activa",
  },
]

export const presupuestos: Presupuesto[] = [
  { id: "pres-1", categoriaId: "cat-3", mes: "2026-01", montoPresupuestadoCLP: 400000 },
  { id: "pres-2", categoriaId: "cat-4", mes: "2026-01", montoPresupuestadoCLP: 250000 },
  { id: "pres-3", categoriaId: "cat-5", mes: "2026-01", montoPresupuestadoCLP: 80000 },
  { id: "pres-4", categoriaId: "cat-6", mes: "2026-01", montoPresupuestadoCLP: 100000 },
  { id: "pres-5", categoriaId: "cat-7", mes: "2026-01", montoPresupuestadoCLP: 120000 },
  { id: "pres-6", categoriaId: "cat-8", mes: "2026-01", montoPresupuestadoCLP: 45000 },
  { id: "pres-7", categoriaId: "cat-9", mes: "2026-01", montoPresupuestadoCLP: 80000 },
  { id: "pres-8", categoriaId: "cat-11", mes: "2026-01", montoPresupuestadoCLP: 30000 },
  { id: "pres-9", categoriaId: "cat-12", mes: "2026-01", montoPresupuestadoCLP: 100000 },
  { id: "pres-10", categoriaId: "cat-14", mes: "2026-01", montoPresupuestadoCLP: 80000 },
]

export const movimientos: Movimiento[] = [
  // Enero 2026 - Ingresos
  {
    id: "mov-1",
    fecha: "2026-01-05",
    descripcion: "Sueldo Enero",
    tipoMovimiento: "Ingreso",
    categoriaId: "cat-1",
    metodoPago: "Transferencia",
    cuentaDestinoId: "cta-1",
    montoCLP: 1500000,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2026-01",
  },
  {
    id: "mov-2",
    fecha: "2026-01-12",
    descripcion: "Freelance - Desarrollo web",
    tipoMovimiento: "Ingreso",
    categoriaId: "cat-2",
    metodoPago: "Transferencia",
    cuentaDestinoId: "cta-1",
    montoCLP: 350000,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2026-01",
  },
  // Gastos fijos Enero
  {
    id: "mov-3",
    fecha: "2026-01-01",
    descripcion: "Arriendo Departamento",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-3",
    tipoGasto: "Fijo",
    metodoPago: "Transferencia",
    cuentaOrigenId: "cta-1",
    montoCLP: 400000,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2026-01",
  },
  {
    id: "mov-4",
    fecha: "2026-01-08",
    descripcion: "Plan Isapre Colmena",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-9",
    tipoGasto: "Fijo",
    metodoPago: "Débito",
    cuentaOrigenId: "cta-1",
    montoCLP: 75000,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2026-01",
  },
  {
    id: "mov-5",
    fecha: "2026-01-10",
    descripcion: "Internet VTR Hogar",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-8",
    tipoGasto: "Fijo",
    metodoPago: "Débito",
    cuentaOrigenId: "cta-1",
    montoCLP: 29990,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2026-01",
  },
  {
    id: "mov-6",
    fecha: "2026-01-10",
    descripcion: "Plan Móvil Entel",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-8",
    tipoGasto: "Fijo",
    metodoPago: "Débito",
    cuentaOrigenId: "cta-1",
    montoCLP: 14990,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2026-01",
  },
  {
    id: "mov-7",
    fecha: "2026-01-12",
    descripcion: "Cuenta Luz Enel",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-7",
    tipoGasto: "Fijo",
    metodoPago: "Transferencia",
    cuentaOrigenId: "cta-1",
    montoCLP: 42000,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2026-01",
  },
  {
    id: "mov-8",
    fecha: "2026-01-12",
    descripcion: "Cuenta Agua Aguas Andinas",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-7",
    tipoGasto: "Fijo",
    metodoPago: "Transferencia",
    cuentaOrigenId: "cta-1",
    montoCLP: 28000,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2026-01",
  },
  {
    id: "mov-9",
    fecha: "2026-01-15",
    descripcion: "Gas Lipigas",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-7",
    tipoGasto: "Fijo",
    metodoPago: "Efectivo",
    cuentaOrigenId: "cta-3",
    montoCLP: 18000,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2026-01",
  },
  // Suscripciones
  {
    id: "mov-10",
    fecha: "2026-01-05",
    descripcion: "Netflix Premium",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-11",
    tipoGasto: "Fijo",
    metodoPago: "Crédito",
    tarjetaCreditoId: "tc-1",
    montoCLP: 8990,
    cuotas: 1,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2026-01",
  },
  {
    id: "mov-11",
    fecha: "2026-01-08",
    descripcion: "Spotify Premium",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-11",
    tipoGasto: "Fijo",
    metodoPago: "Crédito",
    tarjetaCreditoId: "tc-1",
    montoCLP: 6990,
    cuotas: 1,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2026-01",
  },
  {
    id: "mov-12",
    fecha: "2026-01-10",
    descripcion: "Amazon Prime Video",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-11",
    tipoGasto: "Fijo",
    metodoPago: "Crédito",
    tarjetaCreditoId: "tc-2",
    montoCLP: 4990,
    cuotas: 1,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2026-01",
  },
  // Supermercado
  {
    id: "mov-13",
    fecha: "2026-01-03",
    descripcion: "Supermercado Jumbo",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-4",
    tipoGasto: "Variable",
    metodoPago: "Débito",
    cuentaOrigenId: "cta-1",
    montoCLP: 85000,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2026-01",
  },
  {
    id: "mov-14",
    fecha: "2026-01-09",
    descripcion: "Supermercado Líder",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-4",
    tipoGasto: "Variable",
    metodoPago: "Débito",
    cuentaOrigenId: "cta-1",
    montoCLP: 72000,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2026-01",
  },
  {
    id: "mov-15",
    fecha: "2026-01-16",
    descripcion: "Supermercado Unimarc",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-4",
    tipoGasto: "Variable",
    metodoPago: "Crédito",
    tarjetaCreditoId: "tc-1",
    montoCLP: 68000,
    cuotas: 1,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2026-01",
  },
  {
    id: "mov-16",
    fecha: "2026-01-23",
    descripcion: "Supermercado Santa Isabel",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-4",
    tipoGasto: "Variable",
    metodoPago: "Débito",
    cuentaOrigenId: "cta-1",
    montoCLP: 55000,
    estadoConciliacion: "Pendiente",
    mesConciliacion: "2026-01",
  },
  // Transporte
  {
    id: "mov-17",
    fecha: "2026-01-02",
    descripcion: "Carga Tarjeta Bip!",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-5",
    tipoGasto: "Variable",
    metodoPago: "Efectivo",
    cuentaOrigenId: "cta-3",
    montoCLP: 10000,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2026-01",
  },
  {
    id: "mov-18",
    fecha: "2026-01-11",
    descripcion: "Carga Tarjeta Bip!",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-5",
    tipoGasto: "Variable",
    metodoPago: "Efectivo",
    cuentaOrigenId: "cta-3",
    montoCLP: 10000,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2026-01",
  },
  {
    id: "mov-19",
    fecha: "2026-01-20",
    descripcion: "Carga Tarjeta Bip!",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-5",
    tipoGasto: "Variable",
    metodoPago: "Débito",
    cuentaOrigenId: "cta-1",
    montoCLP: 10000,
    estadoConciliacion: "Pendiente",
    mesConciliacion: "2026-01",
  },
  {
    id: "mov-20",
    fecha: "2026-01-14",
    descripcion: "Uber Centro a Casa",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-5",
    tipoGasto: "Variable",
    metodoPago: "Crédito",
    tarjetaCreditoId: "tc-2",
    montoCLP: 8500,
    cuotas: 1,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2026-01",
  },
  {
    id: "mov-21",
    fecha: "2026-01-21",
    descripcion: "Uber al Aeropuerto",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-5",
    tipoGasto: "Ocasional",
    metodoPago: "Crédito",
    tarjetaCreditoId: "tc-2",
    montoCLP: 25000,
    cuotas: 1,
    estadoConciliacion: "Pendiente",
    mesConciliacion: "2026-01",
  },
  // Bencina
  {
    id: "mov-22",
    fecha: "2026-01-04",
    descripcion: "Copec - Bencina 95",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-6",
    tipoGasto: "Variable",
    metodoPago: "Crédito",
    tarjetaCreditoId: "tc-1",
    montoCLP: 45000,
    cuotas: 1,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2026-01",
  },
  {
    id: "mov-23",
    fecha: "2026-01-18",
    descripcion: "Shell - Bencina 97",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-6",
    tipoGasto: "Variable",
    metodoPago: "Crédito",
    tarjetaCreditoId: "tc-1",
    montoCLP: 50000,
    cuotas: 1,
    estadoConciliacion: "Pendiente",
    mesConciliacion: "2026-01",
  },
  // Farmacia
  {
    id: "mov-24",
    fecha: "2026-01-07",
    descripcion: "Farmacia Cruz Verde",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-10",
    tipoGasto: "Variable",
    metodoPago: "Débito",
    cuentaOrigenId: "cta-1",
    montoCLP: 28000,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2026-01",
  },
  {
    id: "mov-25",
    fecha: "2026-01-19",
    descripcion: "Farmacia Salcobrand",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-10",
    tipoGasto: "Variable",
    metodoPago: "Crédito",
    tarjetaCreditoId: "tc-2",
    montoCLP: 15000,
    cuotas: 1,
    estadoConciliacion: "Pendiente",
    mesConciliacion: "2026-01",
  },
  // Delivery y restaurantes
  {
    id: "mov-26",
    fecha: "2026-01-06",
    descripcion: "Pedidos Ya - Sushi",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-12",
    tipoGasto: "Variable",
    metodoPago: "Crédito",
    tarjetaCreditoId: "tc-1",
    montoCLP: 22000,
    cuotas: 1,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2026-01",
  },
  {
    id: "mov-27",
    fecha: "2026-01-13",
    descripcion: "Uber Eats - Pizza",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-12",
    tipoGasto: "Variable",
    metodoPago: "Crédito",
    tarjetaCreditoId: "tc-2",
    montoCLP: 18000,
    cuotas: 1,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2026-01",
  },
  {
    id: "mov-28",
    fecha: "2026-01-17",
    descripcion: "Rappi - Hamburguesa",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-12",
    tipoGasto: "Variable",
    metodoPago: "Crédito",
    tarjetaCreditoId: "tc-1",
    montoCLP: 15000,
    cuotas: 1,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2026-01",
  },
  {
    id: "mov-29",
    fecha: "2026-01-20",
    descripcion: "Restaurante Castillo Forestal",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-12",
    tipoGasto: "Ocasional",
    metodoPago: "Crédito",
    tarjetaCreditoId: "tc-1",
    montoCLP: 45000,
    cuotas: 1,
    estadoConciliacion: "Pendiente",
    mesConciliacion: "2026-01",
  },
  // Entretenimiento
  {
    id: "mov-30",
    fecha: "2026-01-11",
    descripcion: "Cine Cinemark - 2 entradas",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-14",
    tipoGasto: "Ocasional",
    metodoPago: "Crédito",
    tarjetaCreditoId: "tc-2",
    montoCLP: 16000,
    cuotas: 1,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2026-01",
  },
  {
    id: "mov-31",
    fecha: "2026-01-24",
    descripcion: "Entrada Teatro Municipal",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-14",
    tipoGasto: "Ocasional",
    metodoPago: "Crédito",
    tarjetaCreditoId: "tc-1",
    montoCLP: 35000,
    cuotas: 1,
    estadoConciliacion: "Pendiente",
    mesConciliacion: "2026-01",
  },
  // Compras grandes en cuotas
  {
    id: "mov-32",
    fecha: "2026-01-15",
    descripcion: "Notebook Falabella",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-13",
    tipoGasto: "Ocasional",
    metodoPago: "Crédito",
    tarjetaCreditoId: "tc-1",
    montoCLP: 600000,
    cuotas: 6,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2026-01",
  },
  {
    id: "mov-33",
    fecha: "2026-01-22",
    descripcion: "Zapatillas Nike - Paris",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-15",
    tipoGasto: "Ocasional",
    metodoPago: "Crédito",
    tarjetaCreditoId: "tc-2",
    montoCLP: 89990,
    cuotas: 3,
    estadoConciliacion: "Pendiente",
    mesConciliacion: "2026-01",
  },
  // Pagos de tarjetas de crédito
  {
    id: "mov-34",
    fecha: "2026-01-10",
    descripcion: "Pago TC Santander",
    tipoMovimiento: "Transferencia",
    categoriaId: "cat-16",
    metodoPago: "Transferencia",
    cuentaOrigenId: "cta-1",
    tarjetaCreditoId: "tc-1",
    montoCLP: 320000,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2026-01",
  },
  {
    id: "mov-35",
    fecha: "2026-01-25",
    descripcion: "Pago TC BCI",
    tipoMovimiento: "Transferencia",
    categoriaId: "cat-16",
    metodoPago: "Transferencia",
    cuentaOrigenId: "cta-1",
    tarjetaCreditoId: "tc-2",
    montoCLP: 150000,
    estadoConciliacion: "Pendiente",
    mesConciliacion: "2026-01",
  },
  // Aportes a metas
  {
    id: "mov-36",
    fecha: "2026-01-06",
    descripcion: "Aporte Fondo Emergencia",
    tipoMovimiento: "Transferencia",
    categoriaId: "cat-16",
    metodoPago: "Transferencia",
    cuentaOrigenId: "cta-1",
    cuentaDestinoId: "cta-2",
    montoCLP: 250000,
    etiquetas: ["Meta", "Ahorro"],
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2026-01",
  },
  {
    id: "mov-37",
    fecha: "2026-01-06",
    descripcion: "Aporte Viaje Europa",
    tipoMovimiento: "Transferencia",
    categoriaId: "cat-16",
    metodoPago: "Transferencia",
    cuentaOrigenId: "cta-1",
    cuentaDestinoId: "cta-2",
    montoCLP: 150000,
    etiquetas: ["Meta", "Ahorro"],
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2026-01",
  },
  // Diciembre 2025 (mes anterior para comparación)
  {
    id: "mov-100",
    fecha: "2025-12-05",
    descripcion: "Sueldo Diciembre",
    tipoMovimiento: "Ingreso",
    categoriaId: "cat-1",
    metodoPago: "Transferencia",
    cuentaDestinoId: "cta-1",
    montoCLP: 1500000,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2025-12",
  },
  {
    id: "mov-101",
    fecha: "2025-12-01",
    descripcion: "Arriendo Departamento",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-3",
    tipoGasto: "Fijo",
    metodoPago: "Transferencia",
    cuentaOrigenId: "cta-1",
    montoCLP: 400000,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2025-12",
  },
  {
    id: "mov-102",
    fecha: "2025-12-03",
    descripcion: "Supermercado Jumbo",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-4",
    tipoGasto: "Variable",
    metodoPago: "Débito",
    cuentaOrigenId: "cta-1",
    montoCLP: 92000,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2025-12",
  },
  {
    id: "mov-103",
    fecha: "2025-12-08",
    descripcion: "Supermercado Líder",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-4",
    tipoGasto: "Variable",
    metodoPago: "Débito",
    cuentaOrigenId: "cta-1",
    montoCLP: 88000,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2025-12",
  },
  {
    id: "mov-104",
    fecha: "2025-12-15",
    descripcion: "Supermercado Santa Isabel",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-4",
    tipoGasto: "Variable",
    metodoPago: "Crédito",
    tarjetaCreditoId: "tc-1",
    montoCLP: 75000,
    cuotas: 1,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2025-12",
  },
  {
    id: "mov-105",
    fecha: "2025-12-22",
    descripcion: "Supermercado Unimarc",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-4",
    tipoGasto: "Variable",
    metodoPago: "Débito",
    cuentaOrigenId: "cta-1",
    montoCLP: 65000,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2025-12",
  },
  {
    id: "mov-106",
    fecha: "2025-12-08",
    descripcion: "Plan Isapre Colmena",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-9",
    tipoGasto: "Fijo",
    metodoPago: "Débito",
    cuentaOrigenId: "cta-1",
    montoCLP: 75000,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2025-12",
  },
  {
    id: "mov-107",
    fecha: "2025-12-10",
    descripcion: "Internet VTR Hogar",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-8",
    tipoGasto: "Fijo",
    metodoPago: "Débito",
    cuentaOrigenId: "cta-1",
    montoCLP: 29990,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2025-12",
  },
  {
    id: "mov-108",
    fecha: "2025-12-10",
    descripcion: "Plan Móvil Entel",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-8",
    tipoGasto: "Fijo",
    metodoPago: "Débito",
    cuentaOrigenId: "cta-1",
    montoCLP: 14990,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2025-12",
  },
  {
    id: "mov-109",
    fecha: "2025-12-12",
    descripcion: "Cuenta Luz Enel",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-7",
    tipoGasto: "Fijo",
    metodoPago: "Transferencia",
    cuentaOrigenId: "cta-1",
    montoCLP: 48000,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2025-12",
  },
  {
    id: "mov-110",
    fecha: "2025-12-12",
    descripcion: "Cuenta Agua Aguas Andinas",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-7",
    tipoGasto: "Fijo",
    metodoPago: "Transferencia",
    cuentaOrigenId: "cta-1",
    montoCLP: 25000,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2025-12",
  },
  {
    id: "mov-111",
    fecha: "2025-12-05",
    descripcion: "Netflix Premium",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-11",
    tipoGasto: "Fijo",
    metodoPago: "Crédito",
    tarjetaCreditoId: "tc-1",
    montoCLP: 8990,
    cuotas: 1,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2025-12",
  },
  {
    id: "mov-112",
    fecha: "2025-12-08",
    descripcion: "Spotify Premium",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-11",
    tipoGasto: "Fijo",
    metodoPago: "Crédito",
    tarjetaCreditoId: "tc-1",
    montoCLP: 6990,
    cuotas: 1,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2025-12",
  },
  {
    id: "mov-113",
    fecha: "2025-12-02",
    descripcion: "Carga Tarjeta Bip!",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-5",
    tipoGasto: "Variable",
    metodoPago: "Efectivo",
    cuentaOrigenId: "cta-3",
    montoCLP: 10000,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2025-12",
  },
  {
    id: "mov-114",
    fecha: "2025-12-10",
    descripcion: "Carga Tarjeta Bip!",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-5",
    tipoGasto: "Variable",
    metodoPago: "Efectivo",
    cuentaOrigenId: "cta-3",
    montoCLP: 10000,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2025-12",
  },
  {
    id: "mov-115",
    fecha: "2025-12-18",
    descripcion: "Carga Tarjeta Bip!",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-5",
    tipoGasto: "Variable",
    metodoPago: "Débito",
    cuentaOrigenId: "cta-1",
    montoCLP: 10000,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2025-12",
  },
  {
    id: "mov-116",
    fecha: "2025-12-04",
    descripcion: "Copec - Bencina 95",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-6",
    tipoGasto: "Variable",
    metodoPago: "Crédito",
    tarjetaCreditoId: "tc-1",
    montoCLP: 42000,
    cuotas: 1,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2025-12",
  },
  {
    id: "mov-117",
    fecha: "2025-12-16",
    descripcion: "Shell - Bencina 97",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-6",
    tipoGasto: "Variable",
    metodoPago: "Crédito",
    tarjetaCreditoId: "tc-1",
    montoCLP: 48000,
    cuotas: 1,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2025-12",
  },
  {
    id: "mov-118",
    fecha: "2025-12-06",
    descripcion: "Pedidos Ya - Sushi",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-12",
    tipoGasto: "Variable",
    metodoPago: "Crédito",
    tarjetaCreditoId: "tc-1",
    montoCLP: 25000,
    cuotas: 1,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2025-12",
  },
  {
    id: "mov-119",
    fecha: "2025-12-13",
    descripcion: "Uber Eats - Burger King",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-12",
    tipoGasto: "Variable",
    metodoPago: "Crédito",
    tarjetaCreditoId: "tc-2",
    montoCLP: 12000,
    cuotas: 1,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2025-12",
  },
  {
    id: "mov-120",
    fecha: "2025-12-20",
    descripcion: "Restaurante Giratorio",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-12",
    tipoGasto: "Ocasional",
    metodoPago: "Crédito",
    tarjetaCreditoId: "tc-1",
    montoCLP: 55000,
    cuotas: 1,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2025-12",
  },
  {
    id: "mov-121",
    fecha: "2025-12-25",
    descripcion: "Cena Navidad Familia",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-12",
    tipoGasto: "Ocasional",
    metodoPago: "Crédito",
    tarjetaCreditoId: "tc-1",
    montoCLP: 85000,
    cuotas: 3,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2025-12",
  },
  {
    id: "mov-122",
    fecha: "2025-12-07",
    descripcion: "Farmacia Cruz Verde",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-10",
    tipoGasto: "Variable",
    metodoPago: "Débito",
    cuentaOrigenId: "cta-1",
    montoCLP: 32000,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2025-12",
  },
  {
    id: "mov-123",
    fecha: "2025-12-12",
    descripcion: "Cine Hoyts - 2 entradas",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-14",
    tipoGasto: "Ocasional",
    metodoPago: "Crédito",
    tarjetaCreditoId: "tc-2",
    montoCLP: 14000,
    cuotas: 1,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2025-12",
  },
  {
    id: "mov-124",
    fecha: "2025-12-20",
    descripcion: "Regalo Navidad - Ripley",
    tipoMovimiento: "Gasto",
    categoriaId: "cat-15",
    tipoGasto: "Ocasional",
    metodoPago: "Crédito",
    tarjetaCreditoId: "tc-1",
    montoCLP: 120000,
    cuotas: 3,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2025-12",
  },
  {
    id: "mov-125",
    fecha: "2025-12-10",
    descripcion: "Pago TC Santander",
    tipoMovimiento: "Transferencia",
    categoriaId: "cat-16",
    metodoPago: "Transferencia",
    cuentaOrigenId: "cta-1",
    tarjetaCreditoId: "tc-1",
    montoCLP: 280000,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2025-12",
  },
  {
    id: "mov-126",
    fecha: "2025-12-25",
    descripcion: "Pago TC BCI",
    tipoMovimiento: "Transferencia",
    categoriaId: "cat-16",
    metodoPago: "Transferencia",
    cuentaOrigenId: "cta-1",
    tarjetaCreditoId: "tc-2",
    montoCLP: 180000,
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2025-12",
  },
  {
    id: "mov-127",
    fecha: "2025-12-06",
    descripcion: "Aporte Fondo Emergencia",
    tipoMovimiento: "Transferencia",
    categoriaId: "cat-16",
    metodoPago: "Transferencia",
    cuentaOrigenId: "cta-1",
    cuentaDestinoId: "cta-2",
    montoCLP: 200000,
    etiquetas: ["Meta", "Ahorro"],
    estadoConciliacion: "Conciliado",
    mesConciliacion: "2025-12",
  },
]
